/**
 * Google Sheets tab names and column headers. The sheet is the collaborative
 * UI; these headers are the contract between the pipeline and the humans
 * reviewing in Sheets.
 */

export const TAB = {
  config: 'Config',
  pages: 'Pages',
  gscRaw: 'GSC Raw',
  pageContent: 'Page Content',
  queryGroups: 'Query Groups',
  recommendations: 'Recommendations',
  suggestedEdits: 'Suggested Edits',
  rejected: 'Rejected',
  archive: 'Archive',
  newPageIdeas: 'New Page Ideas',
  feedbackRules: 'Feedback Rules',
  clientBrief: 'Client Brief',
  reviewLog: 'Review Log',
} as const;

export const HEADERS: Record<string, string[]> = {
  [TAB.config]: ['Setting', 'Value', 'Notes'],
  [TAB.pages]: [
    'URL',
    'Include in next run',
    'Page type',
    'Primary topic',
    'Target intent',
    'Title tag',
    'H1',
    'Canonical URL',
    'Business priority',
    'Notes',
    'Last analysed',
    'Status',
  ],
  [TAB.gscRaw]: [
    'URL',
    'Query',
    'Clicks',
    'Impressions',
    'CTR',
    'Average position',
    'Start date',
    'End date',
    'Country',
    'Device',
    'Pulled at',
  ],
  [TAB.pageContent]: [
    'URL',
    'HTTP status',
    'Canonical URL',
    'Title tag',
    'Meta description',
    'H1',
    'H2s',
    'Body text',
    'Word count',
    'Last fetched',
  ],
  [TAB.queryGroups]: [
    'URL',
    'Canonical query group',
    'Query variants',
    'Total clicks',
    'Total impressions',
    'Weighted average position',
    'Best query variant',
    'Highest-impression query variant',
    'Variant count',
    'Grouping rationale',
    'Already mentioned on page?',
    'Mention type',
    'Mention evidence',
    'Mention location',
    'Topical relevance score',
    'Intent match score',
    'Commerciality score',
    'Distinct-topic score',
    'Cannibalisation risk score',
    'Better existing URL',
    'Recommendation category',
    'Rationale',
    'Confidence',
  ],
  [TAB.recommendations]: [
    'URL',
    'Recommendation type',
    'Canonical query group',
    'Query variants',
    'Search demand summary',
    'Suggested placement',
    'Suggested content tweak',
    'Existing page evidence',
    'Cannibalisation notes',
    'Priority',
    'Confidence',
    'Review status',
    'Reviewer notes',
    'Corrected recommendation',
    'Corrected canonical query',
    'Corrected group',
    'Better URL',
    'Feedback reason',
    'Remember this rule?',
    'Feedback scope',
  ],
  [TAB.suggestedEdits]: [
    'URL',
    'Edit type',
    'Where on the page',
    'Suggested copy',
    'Keywords targeted',
    'Why',
    'Priority',
    'Confidence',
    'Status',
    'Reviewer notes',
  ],
  [TAB.rejected]: [
    'URL',
    'Recommendation type',
    'Canonical query group',
    'Query variants',
    'Search demand summary',
    'Suggested placement',
    'Suggested content tweak',
    'Existing page evidence',
    'Cannibalisation notes',
    'Priority',
    'Confidence',
    'Review status',
    'Reviewer notes',
    'Corrected recommendation',
    'Corrected canonical query',
    'Corrected group',
    'Better URL',
    'Feedback reason',
    'Remember this rule?',
    'Feedback scope',
  ],
  [TAB.archive]: [
    'Archived at',
    'Source tab',
    'URL',
    'Item',
    'Type',
    'Review status',
    'Reviewer notes',
    'Search demand summary',
    'Details',
  ],
  [TAB.newPageIdeas]: [
    'Suggested page idea',
    'Page type',
    'Commercial or informational',
    'Source URL',
    'Source query group',
    'Supporting query variants',
    'Total impressions',
    'Total clicks',
    'Suggested target intent',
    'Why this should be a separate page',
    'Cannibalisation check',
    'Existing conflicting URL',
    'Suggested URL slug',
    'Internal linking opportunity',
    'Priority',
    'Confidence',
    'Review status',
    'Reviewer notes',
  ],
  [TAB.feedbackRules]: [
    'Rule ID',
    'Created at',
    'Created by',
    'Client',
    'Site / GSC property',
    'Scope',
    'Rule type',
    'Phrase A',
    'Phrase B',
    'Query group',
    'URL',
    'Better URL',
    'Original decision',
    'Corrected decision',
    'Reason',
    'Status',
    'Confidence',
    'Applies from',
    'Applies until',
    'Notes',
  ],
  [TAB.clientBrief]: ['Field', 'Value'],
  [TAB.reviewLog]: [
    'Timestamp',
    'User',
    'URL',
    'Query group',
    'Original decision',
    'Corrected decision',
    'Feedback type',
    'Feedback reason',
    'Rule created?',
    'Rule ID',
  ],
};

/** Human review columns in Recommendations that the tool must never overwrite. */
export const RECOMMENDATION_REVIEW_COLUMNS = [
  'Review status',
  'Reviewer notes',
  'Corrected recommendation',
  'Corrected canonical query',
  'Corrected group',
  'Better URL',
  'Feedback reason',
  'Remember this rule?',
  'Feedback scope',
];

/** Human review columns in New Page Ideas that the tool must never overwrite. */
export const NEW_PAGE_REVIEW_COLUMNS = ['Review status', 'Reviewer notes'];

/** Human review columns in Suggested Edits that the tool must never overwrite. */
export const SUGGESTED_EDIT_REVIEW_COLUMNS = ['Status', 'Reviewer notes'];

/** Tabs that are backend/data tabs and should be hidden from reviewers. */
export const HIDDEN_TABS: string[] = [TAB.gscRaw];

/** Legacy tabs replaced by the unified Pages tab; migrated then hidden. */
export const LEGACY_INPUT_URLS = 'Input URLs';
export const LEGACY_SITE_INVENTORY = 'Site URL Inventory';

/** Columns rendered as real checkboxes (data validation), per tab. */
export const CHECKBOX_COLUMNS: Record<string, string> = {
  [TAB.pages]: 'Include in next run',
};
